export const ADD_NEW_SESSION_TO_STORE = "ADD_NEW_SESSION_TO_STORE";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ASSIGN_SESSION_ID = "ASSIGN_SESSION_ID";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
